{% set name = "chemiscope" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chemiscope-{{ version }}.tar.gz
  sha256: 7d2229531d569fd37112e46e2640a241609311ce07ef7ffce98399a1536c9cfc

build:
  entry_points:
    - chemiscope-input = chemiscope.main:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - jupyterlab >=4.0
    - pip
  run:
    - python >=3.9
    - ase
    - numpy
    - ipywidgets >=7,<9

test:
  imports:
    - chemiscope
  commands:
    - pip check
    - chemiscope-input --help
  requires:
    - pip

about:
  summary: Helpers to work with the chemiscope interactive structure/property explorer for materials and molecules
  home: https://github.com/lab-cosmo/chemiscope
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
